name: Nextcloud
services:
  Nextcloud:
    container_name: Nextcloud
    image: nextcloud:34.0.1-apache@sha256:b52f7bc0e496f227b0e85e3b88571a42c68b6245ccde29d577e733227715dcf5
    restart: unless-stopped
    networks:
      - Nextcloud
      - NextcloudDB
      - NextcloudCache
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=NextcloudDB
      - NEXTCLOUD_ADMIN_USER=${ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - REDIS_HOST=NextcloudCache
      - NEXTCLOUD_TRUSTED_DOMAINS=${HOST}
      - TRUSTED_PROXIES=${TRUSTED_PROXIES}
      - OVERWRITEHOST=${HOST}
      - OVERWRITEPROTOCOL=https
      - OVERWRITECLIURL=https://${HOST}
      - SMTP_SECURE=${SMTP_SECURE}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_NAME=${SMTP_NAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - MAIL_FROM_ADDRESS=noreply
      - MAIL_DOMAIN=${MAIL_DOMAIN}
      - PHP_MEMORY_LIMIT=512M
      - PHP_UPLOAD_LIMIT=32G
      - APACHE_BODY_LIMIT=0
    depends_on:
      NextcloudDB:
        condition: service_healthy
      NextcloudCache:
        condition: service_healthy
    volumes:
      - ${DOCKER_VOLUMES}/Nextcloud/data:/var/www/html
      - /etc/localtime:/etc/localtime:ro
      # Workaround for rootless permission issues (https://help.nextcloud.com/t/nextcloud-containerized-on-synology-with-changed-uid-gid/181714/4)
      - ./overrides/redis-session.ini:/usr/local/etc/php/conf.d/redis-session.ini
      # Allow read_only fs
      - nextcloud_tmp:/tmp

    user: "${UID}:${GID}"
    read_only: true
    tmpfs:
      - /var/run/apache2
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

    logging:
      driver: journald
    healthcheck:
      test: curl -fSs 'http://localhost/status.php' | grep '"installed":true' | grep '"maintenance":false' | grep '"needsDbUpgrade":false' || exit 1
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 30s

    deploy:
      resources:
        limits:
          cpus: 3
          memory: 3GB
          pids: 256

  NextcloudCron:
    container_name: NextcloudCron
    image: nextcloud:34.0.1-apache@sha256:b52f7bc0e496f227b0e85e3b88571a42c68b6245ccde29d577e733227715dcf5
    restart: unless-stopped
    entrypoint: /bin/sh -c 'while true; do php -f /var/www/html/cron.php; sleep 300; done'
    networks:
      - NextcloudDB
      - NextcloudCache
    depends_on:
      Nextcloud:
        condition: service_healthy
    volumes:
      - ${DOCKER_VOLUMES}/Nextcloud/data:/var/www/html
      # Allow read_only fs
      - nextcloud_tmp:/tmp

    logging:
      driver: journald

    user: "${UID}:${GID}"
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 128MB
          pids: 100

  NextcloudDB:
    container_name: NextcloudDB
    image: postgres:18.4-alpine3.23@sha256:996d0920e4ff9df1fc19dacb904492f3c1ec0ec1cc338f0ad7123be7731c5f5e
    restart: unless-stopped
    networks:
      - NextcloudDB
    shm_size: 256M
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${DOCKER_VOLUMES}/Nextcloud/database:/var/lib/postgresql
      - /etc/localtime:/etc/localtime:ro

    user: "${UID}:${GID}"
    read_only: true
    tmpfs:
      - /var/run/postgresql
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

    logging:
      driver: journald
    healthcheck:
      test: pg_isready -U ${DB_USER} -d nextcloud || exit 1
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 15s

    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 512M
          pids: 100

  NextcloudCache:
    container_name: NextcloudCache
    image: redis:8.8.0-alpine3.23@sha256:9d317178eceac8454a2284a9e6df2466b93c745529947f0cd42a0fa9609d7005
    restart: unless-stopped
    command: redis-server --save "" --maxmemory 192mb --maxmemory-policy allkeys-lru
    networks:
      - NextcloudCache

    user: "${UID}:${GID}"
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

    logging:
      driver: journald
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 10s

    deploy:
      resources:
        limits:
          cpus: 0.25
          memory: 256M
          pids: 100

networks:
  Nextcloud:
    external: true
  NextcloudDB:
    external: true
  NextcloudCache:
    external: true

volumes:
  nextcloud_tmp:
