name: Nextcloud
services:
  Nextcloud:
    container_name: Nextcloud
    image: nextcloud:33.0.1-apache@sha256:0b14848e05d19aa25e8a189eb9cfef4215489e0cbf5eb999e8784bf03027c226
    restart: unless-stopped
    networks:
      - Nextcloud
      - NextcloudCache
      - NextcloudDB
    environment:
      - MYSQL_DATABASE=DB
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_HOST=NextcloudDB
      - NEXTCLOUD_ADMIN_USER=${ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - REDIS_HOST=NextcloudCache
      - NEXTCLOUD_TRUSTED_DOMAINS=${HOST}
      - TRUSTED_PROXIES=${TRUSTED_PROXIES}
      - OVERWRITEHOST=${HOST}
      - OVERWRITEPROTOCOL=https
      - OVERWRITECLIURL=https://${HOST}
      - SMTP_SECURE=${SMTP_SECURE}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_NAME=${SMTP_NAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - MAIL_FROM_ADDRESS=noreply
      - MAIL_DOMAIN=${MAIL_DOMAIN}
      - PHP_MEMORY_LIMIT=512M
      - PHP_UPLOAD_LIMIT=32G
      - APACHE_DISABLE_REWRITE_IP=1
      - APACHE_BODY_LIMIT=0
    depends_on:
      - NextcloudDB
      - NextcloudCache
    volumes:
      - ${DOCKER_VOLUMES}/Nextcloud/data:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 1GB

  NextcloudDB:
    container_name: NextcloudDB
    image: mariadb:11.8.6-ubi9@sha256:97fa4c834e2a1fc2b375ef00ec7891ae80c2b408cf11343c1c8ad1aa1655ac7e
    restart: unless-stopped
    networks:
      - NextcloudDB
    environment:
      - MYSQL_DATABASE=DB
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ADMIN_PASSWORD}
    volumes:
      - ${DOCKER_VOLUMES}/Nextcloud/database:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M

  NextcloudCache:
    container_name: NextcloudCache
    image: redis:8.6.2-alpine3.23@sha256:81b6f81d6a6c5b9019231a2e8eb10085e3a139a34f833dcc965a8a959b040b72
    user: "${UID}:${GID}"
    restart: unless-stopped
    command: redis-server --save ""
    networks:
      - NextcloudCache
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

networks:
  Nextcloud:
    external: true
  NextcloudCache:
    external: true
  NextcloudDB:
    external: true
