name: Nextcloud
services:
  Nextcloud:
    container_name: Nextcloud
    image: nextcloud:33.0.3-apache@sha256:b67959acacd54ed2d110e111c8b28c0a87a20129f9427bf5f721a1dc6121decb
    restart: unless-stopped
    networks:
      - Nextcloud
      - NextcloudDB
      - NextcloudCache
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=NextcloudDB
      - NEXTCLOUD_ADMIN_USER=${ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - REDIS_HOST=NextcloudCache
      - NEXTCLOUD_TRUSTED_DOMAINS=${HOST}
      - TRUSTED_PROXIES=${TRUSTED_PROXIES}
      - OVERWRITEHOST=${HOST}
      - OVERWRITEPROTOCOL=https
      - OVERWRITECLIURL=https://${HOST}
      - SMTP_SECURE=${SMTP_SECURE}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_NAME=${SMTP_NAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - MAIL_FROM_ADDRESS=noreply
      - MAIL_DOMAIN=${MAIL_DOMAIN}
      - PHP_MEMORY_LIMIT=512M
      - PHP_UPLOAD_LIMIT=32G
      - APACHE_BODY_LIMIT=0
    depends_on:
      - NextcloudDB
      - NextcloudCache
    volumes:
      - ${DOCKER_VOLUMES}/Nextcloud/data:/var/www/html
      - /etc/localtime:/etc/localtime:ro
      # Workaround for rootless permission issues (https://help.nextcloud.com/t/nextcloud-containerized-on-synology-with-changed-uid-gid/181714/4)
      - ./overrides/redis-session.ini:/usr/local/etc/php/conf.d/redis-session.ini
      # Allow read_only fs
      - nextcloud_tmp:/tmp

    user: "${UID}:${GID}"
    read_only: true
    tmpfs:
      - /var/run/apache2
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

    logging:
      driver: journald
    healthcheck:
      test: curl -fSs 'http://localhost/status.php' | grep '"installed":true' | grep '"maintenance":false' | grep '"needsDbUpgrade":false' || exit 1
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 30s

    deploy:
      resources:
        limits:
          cpus: 2.25
          memory: 1.5GB
          pids: 250

  NextcloudDB:
    container_name: NextcloudDB
    image: postgres:18.4-alpine3.23@sha256:96d56f7f57c6aacd1fcb908bc83b345ec5f83231ee486dd66a1baadce274db88
    restart: unless-stopped
    networks:
      - NextcloudDB
    shm_size: 256M
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${DOCKER_VOLUMES}/Nextcloud/database:/var/lib/postgresql
      - /etc/localtime:/etc/localtime:ro

    user: "${UID}:${GID}"
    read_only: true
    tmpfs:
      - /var/run/postgresql
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

    logging:
      driver: journald
    healthcheck:
      test: pg_isready -U ${DB_USER} -d nextcloud || exit 1
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 15s

    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 512M
          pids: 100

  NextcloudCache:
    container_name: NextcloudCache
    image: redis:8.6.3-alpine3.23@sha256:d146f83b1e0f02fc27c26a50cee39338c736674c5959db84363e6ae3cd9e02d2
    restart: unless-stopped
    command: redis-server --save ""
    networks:
      - NextcloudCache

    user: "${UID}:${GID}"
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

    logging:
      driver: journald
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 10s

    deploy:
      resources:
        limits:
          cpus: 0.25
          memory: 256M
          pids: 100

networks:
  Nextcloud:
    external: true
  NextcloudDB:
    external: true
  NextcloudCache:
    external: true

volumes:
  nextcloud_tmp:
